Repository DevThiagoGalvaoAmorim/Do-it, pull requests merged in 2025-06, with the labels that each got.

#100 Feature/logAtividades✨📢
  mysql/init.sql
  www/controllers/log_atividades.php
  www/models/log_atividades.php
  www/public/Javascript/log_admin.js
  www/public/css/style.css
  www/views/admin/admin_log_view.php
  www/views/admin/admin_stats_view.php
  www/views/admin_view.php
Labels: enhancement, good first issue

#106 Feature/Tela modal de usuário
  www/Test.php
  www/public/Javascript/script.js
  www/public/css/perfil.css
  www/public/css/style.css
  www/public/css/stylePlus.css
  www/views/archives.php
  www/views/folder.php
  www/views/notification.php
  www/views/partials/header.php
  www/views/partials/sidebarAdmin.php
  www/views/perfil.php
  www/views/trash.php
Labels: duplicate, enhancement

#111 Feature/NotasArquivadas
  mysql/init.sql
  www/models/arquivadas_crud.php
  www/models/lixeira_crud.php
  www/models/notas_crud.php
  www/public/Javascript/script.js
  www/views/archives.php
Labels: enhancement
